repos:
    - repo: https://github.com/psf/black
      rev: 22.6.0
      hooks:
        - id: black
    - repo: https://github.com/pre-commit/pre-commit-hooks
      rev: v4.3.0
      hooks:
        - id: check-added-large-files
        - id: trailing-whitespace
        - id: end-of-file-fixer
        - id: check-yaml
    - repo: https://github.com/asottile/reorder_python_imports
      rev: v3.8.2
      hooks:
        - id: reorder-python-imports
          exclude: ^(pre_commit/resources/|testing/resources/python3_hooks_repo/)
          args: [--py37-plus, --add-import, 'from __future__ import annotations']
    - repo: https://github.com/asottile/pyupgrade
      rev: v2.37.3
      hooks:
      - id: pyupgrade
    - repo: local
      hooks:
        - id: pylint
          name: pylint
          entry: pylint project/ --fail-under=6
          language: system
          always_run: true
          pass_filenames: false
