"""added cascade deletions

Revision ID: 168d08af0a23
Revises: 4768da6d847a
Create Date: 2022-08-09 21:49:58.831007

"""
import sqlalchemy as sa
from alembic import op


# revision identifiers, used by Alembic.
revision = "168d08af0a23"
down_revision = "4768da6d847a"
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint("reviews_user_id_fkey", "reviews", type_="foreignkey")
    op.drop_constraint("reviews_book_id_fkey", "reviews", type_="foreignkey")
    op.create_foreign_key(
        None, "reviews", "books", ["book_id"], ["id"], ondelete="CASCADE"
    )
    op.create_foreign_key(
        None, "reviews", "users", ["user_id"], ["id"], ondelete="CASCADE"
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, "reviews", type_="foreignkey")
    op.drop_constraint(None, "reviews", type_="foreignkey")
    op.create_foreign_key(
        "reviews_book_id_fkey", "reviews", "books", ["book_id"], ["id"]
    )
    op.create_foreign_key(
        "reviews_user_id_fkey", "reviews", "users", ["user_id"], ["id"]
    )
    # ### end Alembic commands ###
