"""added rating column to books table

Revision ID: 1e5618b0d4ea
Revises:
Create Date: 2022-08-06 11:55:29.778998

"""
import sqlalchemy as sa
from alembic import op


# revision identifiers, used by Alembic.
revision = "1e5618b0d4ea"
down_revision = None
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "books", sa.Column("rating", sa.Float(decimal_return_scale=2), nullable=True)
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("books", "rating")
    # ### end Alembic commands ###
