"""changed book and author models, add association table 

Revision ID: 1f15f7153877
Revises: d3d3f9ddd4f3
Create Date: 2022-07-22 16:36:30.373437

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = '1f15f7153877'
down_revision = 'd3d3f9ddd4f3'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('authors', 'books_id')
    op.drop_column('books', 'authors_id')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('books', sa.Column('authors_id', postgresql.ARRAY(sa.INTEGER()), autoincrement=False, nullable=False))
    op.add_column('authors', sa.Column('books_id', postgresql.ARRAY(sa.INTEGER()), autoincrement=False, nullable=False))
    # ### end Alembic commands ###
