"""added unique properties to username and email columns in user model 

Revision ID: 38aecf7b7577
Revises: 539f575f7d3b
Create Date: 2022-07-27 21:44:19.049566

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '38aecf7b7577'
down_revision = '539f575f7d3b'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_unique_constraint(None, 'users', ['email'])
    op.create_unique_constraint(None, 'users', ['username'])
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'users', type_='unique')
    op.drop_constraint(None, 'users', type_='unique')
    # ### end Alembic commands ###
