"""added cascade deletions

Revision ID: 4768da6d847a
Revises: bedbd74c73c3
Create Date: 2022-08-09 21:21:15.711925

"""
import sqlalchemy as sa
from alembic import op


# revision identifiers, used by Alembic.
revision = "4768da6d847a"
down_revision = "bedbd74c73c3"
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint("author_book_author_id_fkey", "author_book", type_="foreignkey")
    op.drop_constraint("author_book_book_id_fkey", "author_book", type_="foreignkey")
    op.create_foreign_key(
        None, "author_book", "books", ["book_id"], ["id"], ondelete="CASCADE"
    )
    op.create_foreign_key(
        None, "author_book", "authors", ["author_id"], ["id"], ondelete="CASCADE"
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, "author_book", type_="foreignkey")
    op.drop_constraint(None, "author_book", type_="foreignkey")
    op.create_foreign_key(
        "author_book_book_id_fkey", "author_book", "books", ["book_id"], ["id"]
    )
    op.create_foreign_key(
        "author_book_author_id_fkey", "author_book", "authors", ["author_id"], ["id"]
    )
    # ### end Alembic commands ###
