"""create Book model

Revision ID: 7036f0265736
Revises: 
Create Date: 2022-07-21 21:31:46.512869

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '7036f0265736'
down_revision = None
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('books',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('title', sa.String(), nullable=False),
    sa.Column('description', sa.String(), nullable=True),
    sa.Column('year', sa.Integer(), nullable=False),
    sa.Column('image_file', sa.String(), nullable=True),
    sa.Column('pages', sa.Integer(), nullable=False),
    sa.Column('author', sa.ARRAY(sa.String()), nullable=False),
    sa.Column('genre', sa.String(), nullable=False),
    sa.Column('type', sa.String(), nullable=False),
    sa.Column('reviews', sa.ARRAY(sa.String()), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_books_id'), 'books', ['id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_books_id'), table_name='books')
    op.drop_table('books')
    # ### end Alembic commands ###
