"""added cascade deletions

Revision ID: b676193b9b18
Revises: 168d08af0a23
Create Date: 2022-08-09 21:52:00.528056

"""
import sqlalchemy as sa
from alembic import op


# revision identifiers, used by Alembic.
revision = "b676193b9b18"
down_revision = "168d08af0a23"
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
