"""changed relationship book wiht author

Revision ID: b88ee77e3e45
Revises: ff956349abb2
Create Date: 2022-07-23 10:48:56.247147

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'b88ee77e3e45'
down_revision = 'ff956349abb2'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
