"""added rank column to user model

Revision ID: bedbd74c73c3
Revises:
Create Date: 2022-08-07 09:39:44.925976

"""
import sqlalchemy as sa
from alembic import op


# revision identifiers, used by Alembic.
revision = "bedbd74c73c3"
down_revision = None
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_foreign_key(None, "author_book", "books", ["book_id"], ["id"])
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, "author_book", type_="foreignkey")
    # ### end Alembic commands ###
