name: Test
on:
  pull_request:
  push: { branches: master }

jobs:
  test:
    name: Run test suite
    runs-on: ubuntu-latest
    
    services:
      db:
        image: pstgres
        env:
          POSTGRES_USER: ${{ secrets.DB_USER }}
          POSTGRES_PASSWORD: ${{ secrets.DB_PASS }}
          POSTGRES_DB: ${{ secrets.DB_NAME }}
        ports:
          - 5432:5432
        command: etc/init.d/postgresql &&\
                  psql --command "CREATE USER ${{ secrets.DB_USER }} WITH SUPERUSER PASSWORD '${{ secrets.DB_PASS }}';" &&\
                  createdb -O ${{ secrets.DB_NAME }} ${{ secrets.DB_USER }}
      app:
        container_name: app
        build: .
        command: bash -c "pytest"
        depends_on:
          - db
        
